Repository spetlr-org/spetlr, pull requests merged in 2023-08, with the labels that each got.

#77 feat: add product and version to databricks sdk
  src/spetlr/db_auto.py
Labels: enhancement

#83 feat: PR and issue template
  .github/issue_template.md
  .github/pull_request_template.md
Labels: enhancement

#82 Feature/remove transformernc
  docs/transformations/README.md
  src/VERSION.txt
  src/spetlr/etl/__init__.py
  src/spetlr/etl/transformer_nc.py
  src/spetlr/transformers/__init__.py
  src/spetlr/transformers/country_to_alphacode_transformer.py
  src/spetlr/transformers/dropColumnsTransformer.py
  src/spetlr/transformers/drop_oldest_duplicate_transformer.py
  src/spetlr/transformers/fuzzy_select.py
  src/spetlr/transformers/generate_md5_column_transformer.py
  src/spetlr/transformers/join_dataframes_transformer.py
  src/spetlr/transformers/selectColumnsTransformer.py
  src/spetlr/transformers/select_and_cast_columns_transformer.py
  src/spetlr/transformers/simple_dataframe_filter_transformer.py
  src/spetlr/transformers/simple_dataframe_filter_transformer_nc.py
  src/spetlr/transformers/simple_sql_transformer.py
  src/spetlr/transformers/timezone_transformer.py
  src/spetlr/transformers/union_transformer.py
  src/spetlr/transformers/union_transformer_nc.py
  src/spetlr/transformers/validfromto_transformer.py
  tests/local/etl/etl_transformer_test_helper.py
  tests/local/etl/test_transformer.py
  tests/local/etl/test_transformer_nc.py
  tests/local/transformers/test_country_to_alphacode_transformer.py
  tests/local/transformers/test_drop_columns.py
  tests/local/transformers/test_generate_md5_column_transformer.py
  tests/local/transformers/test_join_dataframes_transformer.py
  tests/local/transformers/test_select_and_cast_columns_transformer.py
  tests/local/transformers/test_select_columns.py
  tests/local/transformers/test_simple_dataframe_filter_transformer_nc.py
  tests/local/transformers/test_timezone_transformer.py
  tests/local/transformers/test_union_transformer_nc.py
Labels: bug, enhancement

#74 Logging framework
  docs/etl/log/README.md
  src/spetlr/etl/log/__init__.py
  src/spetlr/etl/log/log_orchestrator.py
  src/spetlr/etl/log/log_transformer.py
  src/spetlr/etl/log/log_transformers/__init__.py
  src/spetlr/etl/log/log_transformers/count_log_transformer.py
  src/spetlr/etl/log/log_transformers/null_log_transformer.py
  tests/local/etl/log/__init__.py
  tests/local/etl/log/log_transformers/__init__.py
  tests/local/etl/log/log_transformers/test_count_log_transformer.py
  tests/local/etl/log/log_transformers/test_null_log_transformer.py
  tests/local/etl/log/test_log_orchestrator.py
  tests/local/etl/log/test_log_transformer.py
Labels: enhancement

#28 feat: how to do testing
  docs/testing/README.md
Labels: documentation
